language: generic

sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install -y curl parallel cmake wget
  - wget 'https://github.com/google/brotli/archive/v1.0.4.tar.gz'
  - tar zxvf v1.0.4.tar.gz
  - cd brotli-1.0.4/
  - cmake .
  - make
  - sudo cp ./brotli /bin/brotli
  - sudo chmod 777 /bin/brotli
  - cd ..
install:
  - git config --global user.name "Salvador Guzman"
  - git config --global user.email "guzmansalv@gmail.com"
  - git clone 'https://github.com/sguzman/page-silo'
  - cd page-silo
  - mkdir -p txt/
  - cd txt/
script:
  - curl -sq http://23.95.221.108/ | brotli > 1.html.brotli
  - seq 2 $LIMIT | parallel -j8 --joblog /dev/stdout curl -sq http://23.95.221.108/page/'{}'/ '|' brotli '>' '{}'.html.brotli
after_success:
  - git add *.html.brotli
  - git commit -m 'Added brotli pages'
  - echo $GITHUB_AUTH > ~/.git-credentials
  - git config --global credential.helper store
  - git push
